### ISSUE TITLE
Initial implementation

### ISSUE THREAD

**Issue by kkimdev** [m19g/distributed-file-server#2]
Tech stack: NodeJS & Cassandra

Functions:
- Save files in Cassandra.  Create a NodeJS side function that takes 1. file content 2. file extension .  It should save the file in Cassandra with a unique randomly generated name.
- Serve the saved files publicly with NodeJS.

**Comment by kkimdev** [comment]
Note that saving part and serving part should be completely decoupled.

**Comment by arkaray** [comment]
please explain the flow for:
1. image files
2. music files

**Comment by kkimdev** [comment]
Since this is a public repository and the dataflow description is mostly for the main game, I explained at the main repository.  please check the newly assigned issue to you.
